with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: True
packages:
    github.com/nurbekabilev/go-mock-demo/internal/repo:
      interfaces:
        UserRepository:
      