with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: True
# inpackage: True

packages:
    github.com/nurbekabilev/go-mock-demo/internal/repo:
      config:
        all: True
        dir: "./mocks/{{.PackageName}}"

      # interfaces:
        # UserRepository:m
      